-- moved to registries.lua
-- AnthroTraitsGlobals = {
    -- ModID="AnthroTraits",
    -- WorkshopID= 2987213113,
    -- ModVersion = 2.0,
    -- UnwieldyHandsAffectedTimedActions = {"ISBuildAction", "ISCureFliesAction", "ISCureMildewAction", "ISHarvestPlantAction", "ISSeedAction",
                                         -- "ISAddItemInRecipe", "ISAddWaterFromItemAction", "ISBarricadeAction", "ISCraftAction", "ISCutHair",
                                         -- "ISDismantleAction", "ISDyeHair", "ISEjectMagazine", "ISFixAction", "ISFixGenerator", "ISInsertMagazine",
                                         -- "ISLoadBulletsInMagazine", "ISPickupBrokenGlass", "ISPlaceTrap", "ISPlumbItem", "ISRackFirearm",
                                         -- "ISReloadWeaponAction", "ISRemoveBrokenGlass", "ISRemoveBullet", "ISRemoveWeaponUpgrade", "ISStitch",
                                         -- "ISTakePillAction" , "ISTrimBeard", "ISUnbarricadeAction", "ISUnloadBulletsFromFirearm",
                                         -- "ISUnloadBulletsFromMagazine", "ISUpgradeWeapon"},
    -- FoodTags = {"ATCarnivore", "ATHerbivore", "ATInsect", "ATFeralPoison"},
    -- EvolvedRecipeFoodTags = {"ATCarnivore", "ATHerbivore"},
-- }