AnthroTraitsGlobals = {
    ModID="AnthroTraits",
    WorkshopID= 2987213113,
    ModVersion = 1.1,
    UnwieldyHandsAffectedTimedActions = {"ISBuildAction", "ISCureFliesAction", "ISCureMildewAction", "ISHarvestPlantAction", "ISSeedAction",
                                         "ISAddItemInRecipe", "ISAddWaterFromItemAction", "ISBarricadeAction", "ISCraftAction", "ISCutHair",
                                         "ISDismantleAction", "ISDyeHair", "ISEjectMagazine", "ISFixAction", "ISFixGenerator", "ISInsertMagazine",
                                         "ISLoadBulletsInMagazine", "ISPickupBrokenGlass", "ISPlaceTrap", "ISPlumbItem", "ISRackFirearm",
                                         "ISReloadWeaponAction", "ISRemoveBrokenGlass", "ISRemoveBullet", "ISRemoveWeaponUpgrade", "ISStitch",
                                         "ISTakePillAction" , "ISTrimBeard", "ISUnbarricadeAction", "ISUnloadBulletsFromFirearm",
                                         "ISUnloadBulletsFromMagazine", "ISUpgradeWeapon"},
    FoodTags = {"ATCarnivore", "ATHerbivore", "ATInsect", "ATFeralPoison"},
    EvolvedRecipeFoodTags = {"ATCarnivore", "ATHerbivore"},
    ExclaimPhrases = {"AAAH!", "AAAH!", "AAAH!!", "AEIEEEE!", "EAAH!", "AAAGH!"},
    ExclaimPhrasesYeen = {"HAHAHAHAHA!", "HAHAHAHAHA!", "HAHAHAHAHA!!", "HUHEHEHEHAHA!", "HAAAAH!", "HEEEHEEEHAHAHAHA!"},
    ExclaimPhrasesBleater = {"BLEAT!", "BLEAT!", "BLEAT!!", "BLEAAAAT!", "BLEE-EAT!", "EEEEP!"},
}